# Generated by Django 4.2.7 on 2024-02-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Marketplace', '0002_product_available_quantity_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
