# Generated by Django 4.2.7 on 2024-02-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Marketplace', '0003_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
