# Generated by Django 4.2.7 on 2024-02-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Marketplace', '0006_mesaj_orderitem_remove_order_item_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredients',
            new_name='tip',
        ),
    ]
